dist: trusty
language: cpp

matrix:
  fast_finish: false
  include:
    - os: osx
      env:
        - PLATFORM=osx
        - BACKEND=multimedia
      compiler: clang

    - os: linux
      env:
        - PLATFORM=linux
        - BACKEND=mpv
      compiler: gcc
    
    - os: linux
      env:
        - PLATFORM=android
        - BACKEND=multimedia
      compiler: gcc

cache:
  apt: true
  directories:
    - $HOME/Library/Caches/Homebrew
    - $HOME/mpv

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:apt-fast/stable && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get -y -qq install apt-fast; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-fast -y install g++-7 > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew info qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install dmgbuild; fi

install:
  - ci/prepare_$PLATFORM.sh
  - source ci/$PLATFORM.env
  - cd $TRAVIS_BUILD_DIR

script:
  - qmake orion.pro CONFIG+=$BACKEND
  - make -j2
  - mkdir -p artifacts && ci/deploy_$PLATFORM.sh $TRAVIS_BUILD_DIR/artifacts

deploy:
    - provider: releases
      # To use this, create a Github token with the "public_repo" permission, and create an env var GITHUB_API_KEY in the Travis' project settings, making sure "Display value in build log" is set to OFF
      api_key: '$GITHUB_API_KEY'
      file: 
        - 'artifacts/orion-$PLATFORM-$TRAVIS_TAG.dmg'
        - 'artifacts/orion-$PLATFORM-$TRAVIS_TAG.AppImage'
        - 'artifacts/orion-$PLATFORM-$TRAVIS_TAG.apk'
      skip_cleanup: true
      prerelease: true
      on:
        tags: true
        all_branches: true
