# For info about dev tool paths on Appveyor see https://www.appveyor.com/docs/build-environment/#pre-installed-software

environment:
  matrix:
    - platform: x86
      configuration: release
    - platform: x64
      configuration: release
    - platform: x86
      configuration: debug
    - platform: x64
      configuration: debug

install:
  - if %platform%==x86 set QTDIR=C:\Qt\5.8\msvc2015
  - if %platform%==x64 set QTDIR=C:\Qt\5.8\msvc2015_64
  - if %platform%==x86 set PATH=%QTDIR%\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin;%PATH%
  - if %platform%==x64 set PATH=%QTDIR%\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin;%PATH%
  - set INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt
  - if %platform%==x86 set LIB=%QTDIR%\lib;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\lib;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10150.0\ucrt\x86
  - if %platform%==x64 set LIB=%QTDIR%\lib;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\lib\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10150.0\ucrt\x64
  - set VCINSTALLDIR=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
  - if %platform%==x86 set OPENSSL_DIR=C:\OpenSSL-Win32
  - if %platform%==x64 set OPENSSL_DIR=C:\OpenSSL-Win64

build_script:
- cmd: >-
    echo APPVEYOR_BUILD_FOLDER=%APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    qmake orion.pro "CONFIG+=multimedia"

    mkdir libs

    copy /y "%OPENSSL_DIR%\ssleay32.dll" libs

    copy /y "%OPENSSL_DIR%\libeay32.dll" libs

    nmake %configuration%

    %QTDIR%\bin\windeployqt --qmldir src\qml %configuration%\orion.exe

    dir /s

after_build:
  - 7z a orion_%configuration%_%platform%_snapshot_%APPVEYOR_REPO_COMMIT%.zip . -x!.git
  - del %configuration%\*.obj
  - del %configuration%\*.cpp
  - del %configuration%\*.h
  - del %configuration%\*.res
  - if %configuration%==release copy "resources\orion-installer.iss" orion-installer.iss
  - if %configuration%==release "C:\Program Files (x86)\Inno Setup 5\iscc.exe" /DPlatform=%platform% /DAdditionalRedist="C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\1033\vcredist_%platform%.exe" /F"orion-%configuration%-%platform%" "orion-installer.iss"

artifacts:
  - path: orion_$(configuration)_$(platform)_snapshot_$(APPVEYOR_REPO_COMMIT).zip
    name: orion windows $(configuration) $(platform) snapshot zip
  - path: orion-$(configuration)-$(platform).exe
    name: Windows installer

deploy:
- provider: GitHub
  auth_token:
    secure: kna2fyW9Q70WCBxJn/YYJ4pupSRog8FFp6BhKOjr6rtfMIGGtN52UuiMtc90RTla
  artifact: orion-$(configuration)-$(platform).exe
  prerelease: true
  force_update: true
  on:
    configuration: release
